import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

const FAQS = [
  {
    q: 'Is TravelMate really free to use?',
    a: 'Yes — generate itineraries, save trips, and use the multilingual copilot at no cost.',
  },
  {
    q: 'How accurate are the AI-generated itineraries?',
    a: 'Itineraries are generated by Google Gemini based on your destination, budget, and travel style, then paired with real destination images and place data. Always double-check opening hours and prices before booking.',
  },
  {
    q: 'Can I use TravelMate for international trips?',
    a: 'Absolutely — search any city, landmark, or airport worldwide and get a tailored day-by-day plan.',
  },
  {
    q: 'Do I need to create an account?',
    a: 'You can browse freely, but signing in with Google lets you save trips and revisit them anytime from My Trips.',
  },
  {
    q: 'What languages does the AI copilot support?',
    a: 'English, Hindi, French, German, Spanish, Italian, Portuguese, Tamil, Telugu, Malayalam, Kannada, and Marathi, with more being added.',
  },
]

export function FAQSection() {
  return (
    <section className="mx-auto max-w-3xl px-5 py-20 sm:px-8">
      <div className="mb-10 text-center">
        <span className="text-accent-text text-sm font-semibold tracking-wide uppercase">FAQ</span>
        <h2 className="font-display text-3xl font-bold sm:text-4xl">Frequently asked questions</h2>
      </div>
      <Accordion type="single" collapsible className="border-border rounded-2xl border px-4">
        {FAQS.map((faq) => (
          <AccordionItem key={faq.q} value={faq.q}>
            <AccordionTrigger className="text-left">{faq.q}</AccordionTrigger>
            <AccordionContent className="text-muted-foreground">{faq.a}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </section>
  )
}
